name: Deploy

on:
  push:
    branches: [ main, add-github-actions ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:22-alpine # Use Node.js 22 container
    
    steps:
    - run: echo "The job was automatically triggered by a ${{github.event_name}} event."
    - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
    # Checkout the repository
    - name: Check out the repository code
      uses: actions/checkout@v4
    - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
    # Set up node in the runner
    #- name: Use Node.js 22.x
    #  uses: actions/setup-node@v4
    #  with:
    #    node-version: '22.x'
    #    cache: 'npm'
    # Install node dependencies     
    - name: Install dependencies
      run: npm ci      
    # Build the project
    - name: Build
      run: npm run build
    - run: pwd 
    - run: ls -la
    - run: find dist -type f
    # Check if the dist folder exists
    # List files inside the dist folder
    - name: List files in dist folder
      run: find dist -type f -exec stat -c "%10s %n" {} \;