name: Deploy Template

on:
  workflow_call:
    inputs:
      env_name:
        required: true
        type: string
      env_url:
        required: true
        type: string
      cf_branch:
        required: true
        type: string
      artifact_name:
        required: false
        type: string
        default: dist

    secrets:
      CLOUDFLARE_API_TOKEN:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: node:22-alpine
    environment:
      name: ${{ inputs.env_name }}
      url: ${{ inputs.env_url }}
    steps:
      - name: Download dist artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}
          path: dist
      - name: List files in dist folder
        run: find dist -type f -exec stat -c "%10s %n" {} \;
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          # If a push to a non-production branch is done, it will deploy as a preview deployment
          command: pages deploy dist --project-name=devsgowhere
      - name: Print deployment URL
        run: echo $DEPLOYMENT_URL
        env:
          DEPLOYMENT_URL: ${{ steps.deploy.outputs.deployment-url }}