name: (Manual) Event Scrapper

on:
  workflow_dispatch:
    inputs:
      eventURL:
        description: 'Event URL to scrape'
        required: true
        type: string
      orgID:
        description: 'Organization ID to associate with the event'
        required: true
        type: string

jobs:
  create-event:
    # use official Puppeteer image for headless Chrome
    runs-on: ghcr.io/puppeteer/puppeteer:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      - name: Install dependencies
        run: npm ci
        