name: (Scheduled) Nightly Builds

on:
  # Trigger the workflow on:
  # - schedule (daily at midnight UTC) on the default branch (which is main)
  schedule:
    - cron: '0 16 * * *' # Runs daily at midnight +8 GMT (which is 16:00 UTC)

jobs:

  ##########################################
  # Build job
  # - Builds the project and archives the dist folder as an artifact
  # - Runs on push to main or on pull request to main
  ##########################################
  build:
    uses: ./.github/workflows/build-template.yml

##########################################
# Nightly deployment job
# - Deploys the default branch (main) to Cloudflare Pages
# - Runs daily at midnight UTC
##########################################
  deploy-nightly:
    needs: build
    uses: ./.github/workflows/deploy-template.yml
    with:
      env_name: nightly
      env_url: https://devsgowhere.com
      cf_branch: main
    secrets:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}