name: (Pull Request) Preview Builds

on:
  # Run this workflow via manual dispatch. See:
  #   https://docs.github.com/en/actions/managing-workflow-runs-and-deployments/managing-workflow-runs/manually-running-a-workflow#running-a-workflow
  workflow_dispatch:

jobs:

  ##########################################
  # Build job
  # - Builds the project and archives the dist folder as an artifact
  ##########################################
  build:
    uses: ./.github/workflows/build-template.yml

  ##########################################
  # Preview deployment job
  # - Deploys branch preview to Cloudflare Pages
  ##########################################
  deploy-preview:
    needs: build
    uses: ./.github/workflows/deploy-template.yml
    with:
      env_name: preview
      cf_branch: ${{ github.ref_name }}
    secrets: 
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}   
