name: (Manual) Production Builds

on:
  # Trigger the workflow on:
  # - push to main
  push:
    branches: [ main ]

jobs:

  ##########################################
  # Build job
  # - Builds the project and archives the dist folder as an artifact
  # - Runs on push to main or on pull request to main
  ##########################################
  build:
    uses: ./.github/workflows/build-template.yml

  ##########################################
  # Preview deployment job
  # - Deploys branch preview to Cloudflare Pages for each pull request
  ##########################################
  deploy-preview:
    needs: build
    uses: ./.github/workflows/deploy-template.yml
    with:
      env_name: preview
      cf_branch: staging
    secrets: 
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}   

  ##########################################
  # Production deployment job
  # - Deploys main branch to Cloudflare Pages
  # - Only runs on push to main branch
  ##########################################
  deploy-production:
    needs: build
    # only run this job if the event is a push to main branch
    if: github.event_name == 'push' && github.ref_name == 'main'
    uses: ./.github/workflows/deploy-template.yml
    with:
      env_name: production
      cf_branch: main
    secrets:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
